version: "3"

services:
  caddy:
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/ssl/caddy/prod/Caddyfile:/etc/caddy/Caddyfile
      - caddy:/data
    env_file:
      - ./ssl/env/caddy.env
  request:
    restart: always
  api:
    environment: 
      - TARGET=https://prod.host.com
      - DOMAIN=prod.host.com
    restart: always
    

volumes:
  caddy:
